[package]
name = "want"
version = "0.3.1" # remember to update html_root_url
description = "Detect when another Future wants a result."
keywords = ["futures", "channel", "async"]
authors = ["Sean McArthur <sean@seanmonstar.com>"]
license = "MIT"
repository = "https://github.com/seanmonstar/want"
documentation = "https://docs.rs/want"
edition = "2018"

[dependencies]
try-lock = "0.2.4"

[dev-dependencies]
tokio-executor = "0.2.0-alpha.2"
tokio-sync = "0.2.0-alpha.2"
